name: Python API Key Example

on:
  push:
    branches:
      - main  # Se ejecuta cuando haces push a la rama main
  workflow_dispatch:  # Permite ejecutarlo manualmente desde la interfaz de GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Versión de Python que estés usando

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python script.py
        env:
          API_KEY: ${{ secrets.GEMINI_API }}
